### ISSUE TITLE
Invalid dates are throwing an exception

### ISSUE THREAD

**Issue by hrj** [iryndin/jdbf#15]
While trying to read from an old database, I get this exception:
```
java.text.ParseException: Unparseable date: "
at java.text.DateFormat.parse(DateFormat.java:366)
	at net.iryndin.jdbf.util.JdbfUtils.parseDate(Unknown Source)
	at net.iryndin.jdbf.core.DbfRecord.getDate(Unknown Source)
	at net.iryndin.jdbf.core.DbfRecord.toMap(Unknown Source)
```

**Comment by gstockr** [comment]
I am having same issue as well when I use Visual FoxPro table.
